### PR TITLE
doc (completeness checklist): deploy updates

### PR DESCRIPTION
**Pull request by cromwellryan**
**Open Graph**
Open graph tags provide meta data for social networks.  At the 
very least, including the `og:image` adds a nice touch and 
generally avoids sharing an out of context, random image.

**SSL**
Just do it™

### CODE REVIEW

**Comment by cromwellryan** [comment]
@nrambeck @emilykggray I've added two items to the site completeness checklist: SSL and Open Graph.  I feel like we might want to reorganize at some point to get SSL and deployment, in general, up to the top of the list.  :shrug:

**Comment by catheraaine** [comment]
@cromwellryan will you update or close, please!

**Comment by catheraaine** [comment]
@asimpson or @cromwellryan do you want to check in on this? I rebased it.

**Comment by catheraaine** [comment]
closing due to inactivity

**Pull request closed without merging**
