### PR TITLE
feat: start laptop script entry

### PR DESCRIPTION
**Pull request by asimpson**
📝 beginning the documentation for the 💻 script stuff + how we wipe machines down when they are retired/returned. This is just the beginning, I need to find some time to actually take some screenshots and iron out any confusing parts.

### CODE REVIEW

**Comment by cromwellryan** [comment]
Rebased on `master` now that we have gitbook merged (thanks). Also, gitbook doesn't have the concept of a default `readme.md` file in folders, so I updated to root [README.md link](https://github.com/sparkbox/how_to/pull/48/files#diff-04c6e90faac2675aa89e2176d2eec7d8R15)

**Comment by cromwellryan** [comment]
@asimpson where would we put this kind of stuff? Feels closer to dev, but maybe not. ¯\_(ツ)_/¯

**Comment by asimpson** [comment]
Top level item called `Hardware`?

**Comment by cromwellryan** [comment]
I'm not good at this - we need an @emilykggray.

**Comment by emilykggray** [comment]
`Hardware` could make sense. Also, we have a very lonely `Office` section that it feels like both this and the Device Wall could potentially live in.

**Comment by cromwellryan** [comment]
I was thinking about 1password for this section also... office would kinda make sense. or _operations_?

**Comment by emilykggray** [comment]
`Office-y Operations-y Stuff`

**Comment by cromwellryan** [comment]
Alright - office it is

**Comment by cromwellryan** [comment]
or operations... ;)

**Comment by catheraaine** [comment]
@asimpson I'd love if you keep this in there, could you update? 

or close...

**Pull request merged**
