### PR TITLE
Here's the skeleton of changes to make

### PR DESCRIPTION
**Pull request by emilykggray**

### CODE REVIEW

**Comment by cromwellryan** [comment]
Yeah!!

Needs some formatting love, but I'm really excited to see this get flushed out.  Also, please take a look at the results on gitbook which is linked in:

image

**Comment by catheraaine** [comment]
@emilykggray or @amunhofen could you update or close, please?

**Comment by emilykggray** [comment]
It would be great to have someone flesh it out, but I won't have time for awhile.

**Comment by emilykggray** [comment]
I approve.

**Comment by emilykggray** [comment]
I approve.

**Comment by catheraaine** [comment]
I think we've updated the PM file since this pr was last looked at, I'm going to close!

**Pull request closed without merging**
